### ISSUE TITLE
Bug with search function

### ISSUE THREAD

**Issue by trashcluster** [bcc-code/bcc-literature#2]
Steps to reproduce:
1. Go to Literature app 
2. Write name of author in search bar
3. Click enter
4. Choose the author in Filters
5. Delete everything from Search bar,
6. You see the error attached to this email

PS I tried to get all articles from Enok Hansen, just that you understand my behaviour as your user.
![image](https://user-images.githubusercontent.com/33961608/111447127-68f2cf80-870d-11eb-9a18-024df51b02e5.png)

[Bug reported by Aksel N.](https://projects.bcc.no/desk/tickets/6488218)

**Comment by Dr-Wade** [comment]
This issue actually highlights two problems:
- A bug happens when one tries to search using an empty query. This bug is fixed in #8
- The literature app is missing something in the search. It is possible to get all articles written by an author, but it requires to go the author page. It is not possible to do it from the search page, because the book and author filters are applied **after** the Azure Search service returns its search results (based on the search query). Note also that those filters are reset whenever the search query changes. The change requested by Aksel would mean to redefine the whole search flow: we could discuss this in a new issue
